<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class AssetsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $webinars = [
                    // ── Row 1 ─────────────────────────────────────────────
                    [
                        'industry_id'     => null,
                        'title'           => 'GRESB Water Score Benchmarks: Hotel REITs in 2025',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('GRESB Water Score Benchmarks Hotel REITs in 2025'),
                        'category'        => 'Webinar',
                        'tags'            => 'ESG & GRESB Strategy',
                        'description'     => 'Hotel REITs averaged 67.7% on the water indicator — the second-lowest score in the sector. This session explains why it is a documentation problem, not a performance problem, and walks through the three-step fix.',
                        'mini_description'=> '32 min',
                        'video_path'      => 'videos/webinars/gresb-water-score-benchmarks-hotel-reits-2025.mp4',
                        'image_path'      => 'webinars/thumbnails/gresb-water-score-benchmarks.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-04-01',
                        'year_end'        => null,
                        'sort_order'      => 1,
                        'is_featured'     => true,  // Badge NEW
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'Water as a Cap Rate Lever: The Institutional Framework',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('Water as a Cap Rate Lever The Institutional Framework'),
                        'category'        => 'Webinar',
                        'tags'            => 'Financial Analysis',
                        'description'     => 'At a 5.5% cap rate, every $90K in annual water savings equals $1.6M in asset value. This session presents the complete financial model — billing recovery mechanics, NOI bridge analysis, IC presentation format, and Section 179 tax treatment.',
                        'mini_description'=> '41 min',
                        'video_path'      => 'videos/webinars/water-cap-rate-lever-institutional-framework.mp4',
                        'image_path'      => 'webinars/thumbnails/water-cap-rate-lever.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-03-01',
                        'year_end'        => null,
                        'sort_order'      => 2,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'Cooling Towers: The $90K Hidden Liability in Your Portfolio',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('Cooling Towers The 90K Hidden Liability in Your Portfolio'),
                        'category'        => 'Webinar',
                        'tags'            => 'Cooling Tower Optimization',
                        'description'     => 'Most commercial cooling towers run 15–30% above their optimal cost point — and pay sewer charges on water that never enters the sewer. Live walkthrough of WST\'s four-step tower audit process with before/after outcome data.',
                        'mini_description'=> '38 min',
                        'video_path'      => 'videos/webinars/cooling-towers-hidden-liability-portfolio.mp4',
                        'image_path'      => 'webinars/thumbnails/cooling-towers-hidden-liability.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-03-01',
                        'year_end'        => null,
                        'sort_order'      => 3,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],

                    // ── Row 2 ─────────────────────────────────────────────

                    [
                        'industry_id'     => null,
                        'title'           => 'IoT Water Monitoring: 8-Month Payback Explained',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('IoT Water Monitoring 8 Month Payback Explained'),
                        'category'        => 'Webinar',
                        'tags'            => 'Smart Monitoring',
                        'description'     => 'Monthly billing data misses most water cost opportunities. This session covers WST\'s IoT monitoring methodology, the 78 confirmed leak events detected per year in WST\'s portfolio, and how real-time data produces GRESB MR3/RA4 documentation automatically.',
                        'mini_description'=> '29 min',
                        'video_path'      => 'videos/webinars/iot-water-monitoring-payback-explained.mp4',
                        'image_path'      => 'webinars/thumbnails/iot-water-monitoring-payback.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-02-01',
                        'year_end'        => null,
                        'sort_order'      => 4,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'Commercial Water Billing: The 12 Most Common Errors',
                        'sub_title'       => 'Jody Ashton · Partner of Operations, WST',
                        'slug'            => Str::slug('Commercial Water Billing The 12 Most Common Errors'),
                        'category'        => 'Webinar',
                        'tags'            => 'Billing & Recovery',
                        'description'     => 'Rate misclassifications, sewer overcharges on evaporated water, meter multiplier errors — present in 8–12% of commercial property billing. A systematic walkthrough of each error type, the recovery methodology, and what is retroactively recoverable.',
                        'mini_description'=> '44 min',
                        'video_path'      => 'videos/webinars/commercial-water-billing-12-common-errors.mp4',
                        'image_path'      => 'webinars/thumbnails/commercial-water-billing-errors.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-02-01',
                        'year_end'        => null,
                        'sort_order'      => 5,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'Ara AI Platform Live Demo: Portfolio Water Intelligence',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('Ara AI Platform Live Demo Portfolio Water Intelligence'),
                        'category'        => 'Webinar',
                        'tags'            => 'Platform Demo',
                        'description'     => 'A 30-minute live walkthrough of Ara AI — the Water Risk Intelligence Map, AI bill extraction pipeline, Recovery CRM, and GRESB export workflow. Includes a live risk assessment on a five-property sample portfolio.',
                        'mini_description'=> '34 min',
                        'video_path'      => 'videos/webinars/ara-ai-platform-live-demo-portfolio-water-intelligence.mp4',
                        'image_path'      => 'webinars/thumbnails/ara-ai-platform-demo.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2026-01-01',
                        'year_end'        => null,
                        'sort_order'      => 6,
                        'is_featured'     => true,  // Badge NEW
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],

                    // ── Tambahan webinar ──────────────────────────────────

                    [
                        'industry_id'     => null,
                        'title'           => 'GRESB WT1 Data Coverage: Using Ara AI to Close the Gap',
                        'sub_title'       => 'Clifford Campbell · Partner, WST',
                        'slug'            => Str::slug('GRESB WT1 Data Coverage Using Ara AI to Close the Gap'),
                        'category'        => 'Webinar',
                        'tags'            => 'ESG & GRESB Strategy',
                        'description'     => 'WT1 coverage is the highest-weighted sub-component of the GRESB water indicator. This session demonstrates how Ara AI\'s automated bill acquisition closes data gaps across large portfolios in advance of the annual submission deadline.',
                        'mini_description'=> '36 min',
                        'video_path'      => 'videos/webinars/gresb-wt1-data-coverage-ara-ai.mp4',
                        'image_path'      => 'webinars/thumbnails/gresb-wt1-coverage-ara-ai.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2025-12-01',
                        'year_end'        => null,
                        'sort_order'      => 7,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'CMS Water Management Plans: IoT Documentation for Healthcare',
                        'sub_title'       => 'Jody Ashton · Partner of Operations, WST',
                        'slug'            => Str::slug('CMS Water Management Plans IoT Documentation for Healthcare'),
                        'category'        => 'Webinar',
                        'tags'            => 'Regulatory & Compliance',
                        'description'     => 'CMS survey readiness for water management programmes requires continuous documentation. This session covers how IoT monitoring of domestic hot water, cooling towers, and dead legs produces the evidence record that surveyors expect.',
                        'mini_description'=> '31 min',
                        'video_path'      => 'videos/webinars/cms-water-management-iot-documentation-healthcare.mp4',
                        'image_path'      => 'webinars/thumbnails/cms-water-management-iot.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2025-11-01',
                        'year_end'        => null,
                        'sort_order'      => 8,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                    [
                        'industry_id'     => null,
                        'title'           => 'Sewer Exemptions: The $8,400 Annual Credit Most Properties Miss',
                        'sub_title'       => 'Jody Ashton · Partner of Operations, WST',
                        'slug'            => Str::slug('Sewer Exemptions The 8400 Annual Credit Most Properties Miss'),
                        'category'        => 'Webinar',
                        'tags'            => 'Billing & Recovery',
                        'description'     => 'Municipal sewer exemptions for cooling tower make-up water and irrigation are available in most US jurisdictions — but fewer than 30% of eligible properties claim them. Step-by-step walkthrough of the identification, application, and back-billing recovery process.',
                        'mini_description'=> '27 min',
                        'video_path'      => 'videos/webinars/sewer-exemptions-annual-credit-properties.mp4',
                        'image_path'      => 'webinars/thumbnails/sewer-exemptions-annual-credit.jpg',
                        'html_content'    => null,
                        'location'        => null,
                        'year_start'      => '2025-10-01',
                        'year_end'        => null,
                        'sort_order'      => 9,
                        'is_featured'     => false,
                        'is_active'       => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ],
                ];


        DB::table('assets')->insert($webinars);

        DB::table('assets')->insert([
            [
                'title'       => 'Maximizing Flow Efficiency in Commercial Buildings',
                'slug'        => Str::slug('Maximizing Flow Efficiency in Commercial Buildings'),
                'category'    => 'white-paper',
                'tags'        => 'FlowManagement',
                'description' => 'Discover how flow management systems reduce water and sewer costs by up to 30% across property portfolios.',
                'image_path'  => 'industries/hotel_industry_water_savings_2.jpeg',
                'sort_order'  => 1,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Water Treatment Optimization for Cooling Towers',
                'slug'        => Str::slug('Water Treatment Optimization for Cooling Towers'),
                'category'    => 'white-paper',
                'tags'        => 'CoolingTowers',
                'description' => 'Learn about chemical-free water treatment technologies that improve cooling tower efficiency, reduce scale, and lower operating costs.',
                'image_path'  => 'industries/office_building_water_efficiency_1.jpeg',
                'sort_order'  => 2,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Smart Water Monitoring in Educational Facilities',
                'slug'        => Str::slug('Smart Water Monitoring in Educational Facilities'),
                'category'    => 'white-paper',
                'tags'        => 'Education,SmartMonitoring',
                'description' => 'Explore the benefits of real-time water monitoring systems in schools to detect leaks, improve safety, and support sustainability goals.',
                'image_path'  => 'industries/campus_water_efficiency_2.jpeg',
                'sort_order'  => 3,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ]);


        DB::table('assets')->insert([
            [
                'title'       => 'Whole Building',
                'slug'        => Str::slug('Whole Building'),
                'category'    => 'tool',
                'tags'        => 'Assessment,Consumption',
                'description' => 'Assess your building’s total daily consumption. Uncover high-usage periods and optimize across systems.',
                'image_path'  => 'tools/icon-whole-building.png', // Pastikan file gambar ada di storage
                'sort_order'  => 5,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Cooling Tower',
                'slug'        => Str::slug('Cooling Tower'),
                'category'    => 'tool',
                'tags'        => 'HVAC,Efficiency',
                'description' => 'Monitor blowdown, cycles of concentration, and make-up water. Cooling towers can account for 30–50% of usage.',
                'image_path'  => 'tools/icon-cooling-tower.png', // Pastikan file gambar ada di storage
                'sort_order'  => 6,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Toilets',
                'slug'        => Str::slug('Toilets'),
                'category'    => 'tool',
                'tags'        => 'Restroom,Leaks',
                'description' => 'Toilets waste up to 200 gallons per day in older systems. Pinpoint inefficiencies and get savings instantly.',
                'image_path'  => 'tools/icon-toilets.png', // Pastikan file gambar ada di storage
                'sort_order'  => 7,
                'is_active'   => 1,
                'is_featured' => 0,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ]);
    }
}
